### ISSUE TITLE
Vulkan create info enchaced mode?

### ISSUE THREAD

**Issue by acterhd** [nvpro-pipeline/vkcpp#63]
Hello. I have suggestion for vectorize some elements. 

```
vk::DescriptorSetLayoutCreateInfo layout = vk::DescriptorSetLayoutCreateInfo()
.bindingCount(bindings.size()).pBindings(bindings.data())
```

TO: 

```
vk::DescriptorSetLayoutCreateInfo layout = vk::DescriptorSetLayoutCreateInfo()
.vBindings(&binding)
//.aBindings(&binding) //Use as std array 
```

**Comment by mtavenrath** [comment]
I agree that it would be desirable to have this feature. In contrast to the functions where we support the vectorized which just get the pointer for a temporary operation the structs keep the pointer until they're used. Due to the extended lifetime of the structs we decided not to accept std::array/std::vector as input to avoid potential programming errors.

Once we have a secure way to handle the ownership we'll add this feature.

**Comment by acterhd** [comment]
In vector have ".data()" and ".size()". Why not?

**Comment by mtavenrath** [comment]
Because of 'ownership' of the data. vector.data() just lives as long as the vector is not internally resized and not deleted. It'd be possible to write this piece of code without any chance of error checking:

`vk::DescriptorSetLayoutCreateInfo layout = vk::DescriptorSetLayoutCreateInfo().aBindings({a,b,c,d})`;

This will create a temporary vector which is valid for the current line. If we want to allow such a syntax we have to ensure that the data is being copied and kept inside our structs.
