### ISSUE TITLE
Null references are UB

### ISSUE THREAD

**Issue by Ralith** [nvpro-pipeline/vkcpp#68]
Excerpt from N3337, §8.3.2/5
> [ Note: in particular, a null reference cannot exist in a well-defined program, because the only way to create such a reference would be to bind it to the “object” obtained by dereferencing a null pointer,which causes undefined behavior. As described in 9.6, a reference cannot be bound directly to a bit-field. — end note ]

vkcpp define static `null` member functions which do exactly this, and encourages their use. While popular compilers may or may not do surprising things there in practice, that can change at any point. The use of such expressions also sets off debugging tools such as clang/gcc's UndefinedBehaviorSanitizer, which makes it more difficult to identify issues in user code. These errors cannot reliably be manually suppressed.

It's unclear what the purpose of using references is in these cases, as they sacrifice well-definedness of the entire program merely to provide pointer-like functionality, when outright use of pointers would not represent a significant burden on the library user.

One solution to this would be to use pointers instead of references for optional arguments to enhanced functions. Accompanied by the removal of the `null` member functions, this would improve usability and safety by providing type-level documentation that enhanced function arguments which are references must always be supplied with a valid object, while those that are pointers may be optional.

**Comment by gbxor** [comment]
I decided to avoid the use of VKCPP_ENHANCED_MODE at all because of its strange usage of references as well. The fact that vk::AllocationCallbacks parameters are passed as a const reference disallows not using AllocationCallbacks without any hack in the code.

**Comment by mtavenrath** [comment]
> Excerpt from N3337, §8.3.2/5

That's a good point. We need to rethink how to pass the nullptr for optional arguments. Going back to pointers is not the preferred choice since it adds all the dereferencing. Generating all allowed combinations of functions might cause combinatory explosions for some functions (not checked yet). 

@Ralith, @gbxor 
A special temporary class which accepts either a reference or a nullptr might be a viable solution in those cases. How about a class like this:

<pre>
template &lt;typename RefType&gt; class OptionalRef
{
public:
  OptionalRef() { m_ptr = nullptr; }
  OptionalRef(void*) { m_ptr = nullptr; }
  OptionalRef(RefType &ref) { m_ptr = &ref };

private:
  RefType *ptr;
}
</pre>

Functions getting optional refererences would be changed to

`void function(OptionalRef<AllocationCallback> const&callback)'

This way you could call function(nullptr), function(myAllocationCallback) and function(OptionalRef<AllocationCallback>())

**Comment by Ralith** [comment]
> Going back to pointers is not the preferred choice since it adds all the dereferencing.

Can you elaborate on this? I'm not sure where additional dereferencing would arise in user code. Any user code that works with with references would work with pointers just by a light sprinkling of `&`. Surely typing one additional character isn't that much to ask, especially as use of pointers as optional arguments is a reasonably common idiom.

> How about a class like this:

The proposed class should work, even if I don't entirely see the need. I would replace the `void*` overload with a `std::nullptr_t` overload if construction from `nullptr` is strongly desired, or maybe remove that overload entirely, since the expression `{}` alone should typically be adequate to default-construct the class. I'd also mark the member functions constexpr and add the usual set of conversion operators.

**Comment by mtavenrath** [comment]
>> Going back to pointers is not the preferred choice since it adds all the dereferencing.
>Can you elaborate on this

When passing `Type const &`you can write `function( {constructor values for Type} );` and the compiler will create a temporary object for the function call. This is not possible when passing pointers. If the signature is `Type const *`  the expression `function( &{constructor values} )` will not compile. Being able to pass temporary objects is a key feature of the layer we want to keep.

The `nullptr` syntax is explicit might be required to be more explicit. Since the additional class should be as invisible as possible a call like `function( {} )` should call function with the empty constructor for `Type` not function with a `nullptr`.

**Comment by Ralith** [comment]
> Being able to pass temporary objects is a key feature of the layer we want to keep.

Ah, right. Been reading too much C11 lately. Makes sense!

> The `nullptr` syntax is explicit might be required to be more explicit. Since the additional class should be as invisible as possible a call like `function( {} )` should call function with the empty constructor for `Type` not function with a `nullptr`.

A call like `function({})` where `function` takes your example `OptionalRef` would invoke `OptionalRef`'s default constructor, which initializes the member pointer to `nullptr`. If you wanted it to provide a default-constructed `RefType` value instead, where would you store that value? If you want to make `OptionalRef` invisible in general you'll also need to use forwarding constructors instead of the non-const you used in the example, which would introduce ambiguity in cases where `RefType` has a constructor which could accept a single nullptr. I don't think it's possible or even desirable to provide optional arguments without requiring any additional syntax from the user at all.

Another option would be to take the optional arguments by value using `std::experimental::optional` instead. I'm not sure what other tradeoffs this might incur; in principle the extra copying is undesirable, but most of the types we're concerned with are very small.

**Comment by mtavenrath** [comment]
Added support for Optional<T> for cases where references can be optional now without the illegal *nullptr hack.
