### ISSUE TITLE
Problem with unexported extension functions

### ISSUE THREAD

**Issue by KeepItOneHundred** [nvpro-pipeline/vkcpp#95]
When I call the vk::Instance::createDebugReportCallbackEXT interface, my code is unable to link since the LunarG loader doesn't export a wrapper for vkCreateDebugReportCallbackEXT and vkcpp doesn't load the function pointer itself.

What's the preferred way to deal with this? Am I missing something obvious?

**Comment by mtavenrath** [comment]
Unless you '#define VK_NO_PROTOTYPES' vulkan.h will provide this prototype for 'vkCreateDebugReportCallbackEXT':

VKAPI_ATTR VkResult VKAPI_CALL vkCreateDebugReportCallbackEXT(
    VkInstance                                  instance,
    const VkDebugReportCallbackCreateInfoEXT*   pCreateInfo,
    const VkAllocationCallbacks*                pAllocator,
    VkDebugReportCallbackEXT*                   pCallback);

Unfortunately the vulkan loader does not provide an implementation for this function which results in the described linker error. To resolve the issue you have to fetch the function pointer like this : 'PFN_vkCreateDebugReportCallbackEXT pfnCreateDebugReportCallback = instance.getProcAddr("vkCreateDebugReportCallbackEXT")' 

and implement the function vkCreateDebugReportCallbackEXT by caling pfnCreateDebugReportCallback.

Note that vkcpp is a header-only library which relies on a loader and we're not attempting to add loader functionality in the future since it's not possible as long as it is a header only library.
